### ISSUE TITLE
Allow Globals to be used throughout the snippets

### ISSUE THREAD

**Issue by stay-lucky** [thejsninja/syrup#3]
Allow Globals to be used throughout the snippets
----
For example, so you don't have to require('assert') in all snippets

**Comment by lgoldstien** [comment]
I can achieve this by allowing you to register global variables within the workers, something like:

```javascript
syrup.inject('Assert', require('assert'));
```

in your main syrup file (where the scenarios are defined)

Is this fit for your purposes?

**Comment by stay-lucky** [comment]
If it means the assert library (and other libraries such as should.js) can be used through all snippets, then yes

**Comment by lgoldstien** [comment]
This has been resolved with e818124db295e0b21715b30cb6610122071d9814 you can take a look at https://github.com/thejsninja/syrup/tree/develop/examples/registered_globals for an example of how to use this.
