### ISSUE TITLE
Scenario dependants cause the scenario to not run

### ISSUE THREAD

**Issue by stay-lucky** [thejsninja/syrup#5]
I have found that specifying a dependant for a scenario causes the scenario to not run. The selenium node starts the browser, but the test does not start.

In the following example scenario 1 will run, finish and the session is closed. Then, scenario 2 will start the browser but the test does not run. 

syrup.scenario('scenario1', `./scenarios/scenario1, [], 'ChromeBrowser');
syrup.scenario('scenario2', `./scenarios/scenario2`, ['scenario1'], 'ChromeBrowser');

IF you do not specify a dependant for scenario 2, it will run it.

syrup.scenario('scenario1', `./scenarios/scenario1, [], 'ChromeBrowser');
syrup.scenario('scenario2', `./scenarios/scenario2`, [], 'ChromeBrowser');

**Comment by lgoldstien** [comment]
To me this sounds like the first scenario isn't finishing up properly. I've tested using the example scripts and cannot replicate the issue you are having. Can you check the console example and see if you're having the same problems?

If not can you provide a full example with the scenario files as well?

**Comment by lgoldstien** [comment]
I found this issue was down to the data being used in the regression suite in question. Closing this as the issue has been resolved in b64b58e7dd2db1ac9a629e06199332737a0c8187 with the addition of a deep extend method.
